vCon Templates
datatrails/datatrails-docs pull request #912
Opened 2024-10-11 00:02 UTC by SteveLasker

Adds a new Templates section to the docs, enabling a collection of industry, vertical, and partner templates.

2024-10-15 09:05 UTC, rcoxhill-01 commented on content/developers/templates/vcons/index.md
> +`arc_display_type` is also the default means to [configure permissions](https://docs.datatrails.ai/platform/administration/sharing-access-inside-your-tenant/) for which type of events a client my vie
"my" -> "may"

2024-10-15 09:07 UTC, rcoxhill-01 commented on content/developers/templates/vcons/index.md
> +The hash algorithm used to has the vCon.
"has" -> "hash"

2024-10-15 09:09 UTC, rcoxhill-01 commented on content/developers/templates/vcons/index.md
> +The hash of the vCon as its recorded on DataTrails.
"its" -> "it is" or "it's"

2024-10-15 09:10 UTC, rcoxhill-01 commented on content/developers/templates/vcons/index.md
> +In the [conserver model](https://www.conserver.io/), these are called chains which run one ore more links.
"ore" -> "or"

2024-10-15 09:12 UTC, rcoxhill-01 commented on content/developers/templates/vcons/index.md
> +For example: (`DataTrails-Partner-ID:synsation.io"`
Missing ")"

2024-10-15 09:27 UTC, JAG-UK requested changes

2024-10-15 09:27 UTC, JAG-UK commented on content/developers/templates/vcons/index.md
> +For the purposes of permissions, this property is a duplicate of the [vcon_operation](#vcon_operation)
```suggestion
For simplicity in configuring permissions, this property is a duplicate of the [vcon_operation](#vcon_operation) but could vary in advanced scenarios.
```

2024-10-15 09:27 UTC, JAG-UK commented on content/developers/templates/vcons/index.md
> +The lifecycle events of a vCon will likely evolve as a standard.
```suggestion
The defined lifecycle events of a vCon will likely evolve with the standard.
```

2024-10-16 08:51 UTC, JAG-UK approved these changes
LGTM

2024-10-16 15:08 UTC, merged